local x = {}
local f, g
g = function(...) end
function f()
    local y = x[g(if _G.__DEV__ then "blue" else "black")]
    y = if _G.__PROFILING__ then 31337 else 90210
    y = x[g(if _G.__DEV__ then "blue" else "black")][x["fog"] or "clear"]
    y = if _G.__PROFILING__ then 31337 else 90210
    y = x[g(if _G.__DEV__ then "blue" else "black")]()
    y = if _G.__PROFILING__ then 31337 else 90210
    y = x[g(if _G.__DEV__ then "blue" else "black")]
    y = if _G.__PROFILING__ then 31337 else 90210
    y = x[g(if _G.__DEV__ then "blue" else "black")]
    y = if _G.__PROFILING__ then 31337 else 90210
    y = x[g(if _G.__DEV__ then "blue" else "black")]
    y = if _G.__PROFILING__ then 31337 else 90210
    y = x[g(if _G.__DEV__ then "blue" else "black")]
    y = if _G.__PROFILING__ then 31337 else 90210
    y = x[g(if _G.__DEV__ then "blue" else "black")]
    y = if _G.__PROFILING__ then 31337 else 90210
    y = x[g(if _G.__DEV__ then "blue" else "black")]
    y = if _G.__PROFILING__ then 31337 else 90210
    y = x[g(if _G.__DEV__ then "blue" else "black")]
    y = if _G.__PROFILING__ then 31337 else 90210
    y = x[g(if _G.__DEV__ then "blue" else "black")]
    y = if _G.__PROFILING__ then 31337 else 90210
    y = x[g(if _G.__DEV__ then "blue" else "black")]
    y = if _G.__PROFILING__ then 31337 else 90210
    y = x[g(if _G.__DEV__ then "blue" else "black")]
    y = if _G.__PROFILING__ then 31337 else 90210
    y = x[g(if _G.__DEV__ then "blue" else "black")]
    y = if _G.__PROFILING__ then 31337 else 90210
    y = x[g(if _G.__DEV__ then "blue" else "black")]
    y = if _G.__PROFILING__ then 31337 else 90210
    y = x[g(if _G.__DEV__ then "blue" else "black")]
    y = if _G.__PROFILING__ then 31337 else 90210
    y = x[g(if _G.__DEV__ then "blue" else "black")]
    y = if _G.__PROFILING__ then 31337 else 90210
    y = x[g(if _G.__DEV__ then "blue" else "black")]
    y = if _G.__PROFILING__ then 31337 else 90210
    y = x[g(if _G.__DEV__ then "blue" else "black")]
    y = if _G.__PROFILING__ then 31337 else 90210
    y = x[g(if _G.__DEV__ then "blue" else "black")]
    y = if _G.__PROFILING__ then 31337 else 90210
end